# Generated by Django 5.2.8 on 2025-11-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_imagen_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default='Descripción no disponible'),
            preserve_default=False,
        ),
    ]
