# Generated by Django 5.2.8 on 2025-12-01 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_destacado_alter_producto_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=200)),
                ('tag', models.CharField(default='NUEVO', max_length=50)),
                ('imagen', models.ImageField(upload_to='banners/')),
                ('color_fondo', models.CharField(default='bg-green-600', help_text='Clase de Tailwind ej: bg-red-500 o un código Hex', max_length=50)),
                ('color_texto', models.CharField(default='text-white', max_length=50)),
                ('texto_boton', models.CharField(default='VER MÁS', max_length=50)),
                ('enlace', models.CharField(default='/productos', max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
